version: "3"
services:
  app:
    build: .
    links:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
    logging:
      driver: none
    command: mongod --quiet --logpath /dev/null

    # THIS DON'T WORK UNTIL DOCKER FIX IT
volumes:
  mongodata:
